### ISSUE TITLE
non issue for me

### ISSUE THREAD

**Issue by techpro2004** [lart2150/kmttg#10]
Just updated to 2.7-l. I noticed the update mechanism did not delete the zip file after updating. Not an issue for me but may be for someone with a smaller c drive. I also have many npl*.tmp files. Maybe those should get cleaned up when they are no longer needed. I am on java 11. As I said, this is an non issue, just something I noticed. Thanks.

**Comment by lart2150** [comment]
I'm changing the updater download to go into the temp folder.  I'm also changing the temp folder so it will make a sub folder and clear out that folder on startup.  This won't help with the next update but it should fix the update after that.  it should also fix NPL tmp files that didn't get cleaned up.
