### ISSUE TITLE
VideoReDo Project file is invalid

### ISSUE THREAD

**Issue by wireman121** [lart2150/kmttg#12]
Using VideoReDo TV Suite Version 6.63.7.836
Using ComSkip to ad detect and then VRD to verify

This method used to work, however for some reason now the VPrj file is invalid.
Looking at a VPrj file that VRD 6 creates looks very different.

**Comment by thess** [comment]
With limited testing, I have been unable to reproduce this problem. I do have VRD TV Suite 6 (6.63.7.835) and have not seen any issues with VPrj files. Check your setup of VRD and make sure there a no older versions laying around. Did this just happen after you updated something?

Also, you did not mention any configuration and/or versions of installed software other than VRD. Some additional information is required - like a log output showing the error.

**Comment by lart2150** [comment]
I don't have VidoReDo.  Wireman can you attach a copy of the vprj file in addition to the troubleshooting ideas thess posted.

**Comment by wireman121** [comment]
Sorry for the delay.
I am posting 2 files.
1 file is what is being created  by KMTTG when asked to use comskip for adscan, but use VRD for everything else.  KMTTG is converting the comskip output file to something that VRD can read, and then VRD should be displaying the cuts for review, once I close VRD, VRD should perform the cuts.

The other file is what is produced by VRD when I manually ask it to scan for commercials.

The reason I use this scenario is because comskip is leaps and bounds better at detecting commercials than VRD is, but VRD for review and cutting is way better than the alternatives.

Realistically, I dont even care about the cutting, because I'm strictly using KMTTG to use comskip to detect commercials, allow me to review in VRD and then just save without cutting, since I'm relying on KMTTG to skip commercials in realtime.
What is happening, from my perspective, is that comskip is producing the correct file, but when KMTTG is converting it to something VRD can read, its converting to a "version 2" format, and it appears that VRD TV Suite 6 can no longer read the Version 2 format?  There is quite a difference in file structure.

Am I incorrect in assuming that KMTTG is doing the conversion from comskip output to the vprj format?  If so, where does that take place?

Wondering if version .836 is where support for version 2 files was dumped?

https://we.tl/t-4aYtyCqVWK

**Comment by thess** [comment]
Looks like your version of **comskip** is either old or mis-configured. You need to have the following in your `comskip.ini` file:
`
output_videoredo3=1
`
... otherwise, you will get the output you are seeing.

**Comment by wireman121** [comment]
That fixed it!! Thanks!

**Comment by lart2150** [comment]
Thank you thess for the assist.
