### ISSUE TITLE
macos: kmttg_v2.8-l crashes on launch

### ISSUE THREAD

**Issue by allartburns** [lart2150/kmttg#22]
This is on 10.13.6 (17G14042).

Running kmttg_v2.7-l just fine, jre-8u411-macosx-x64 installed, java crashes on launch.
Is there something else i need to install?  I remember with v2.7 there was something I had to install by hand but I'm not finding my notes. I ran meld on both kmttg folders and the saw that 2.8 is running javafx-sdk-19.0.2.1 but nothing else that seems like an obvious problem.

[crash.txt](https://github.com/lart2150/kmttg/files/15210536/crash.txt)

**Comment by allartburns** [comment]
Tested the same release on my W11 laptop and it works just fine.

**Comment by lart2150** [comment]
JRE 8 should have fix built in.  Can you try a more recent version of openjre like 11, 17 or 21?

https://adoptium.net/temurin/releases/?version=17&package=jre&os=mac

**Comment by allartburns** [comment]
Just installed 17, rebooted, still crashes.
[crash.txt](https://github.com/lart2150/kmttg/files/15210723/crash.txt)

**Comment by allartburns** [comment]
I'm going to go through my filesystem and ditch all the java bundles I'm not using and see if that cleans anything up.

**Comment by lart2150** [comment]
that second crash dump was still java 8u411

**Comment by allartburns** [comment]
Crumbs, sorry.  I'm a C/C++ person and kinda ignorant about Java.  8u411 is the Oracle installed JRE.

I've also installed these:
flatline:JavaVirtualMachines jet$ ls -l
total 0
drwxr-xr-x  3 root  wheel  96 May  4 17:11 jdk-22.jdk
drwxr-xr-x  3 root  wheel  96 Mar 30  2017 jdk1.8.0_121.jdk
drwxr-xr-x  3 root  wheel  96 Jan 18  2023 temurin-11.jdk
drwxr-xr-x  3 root  wheel  96 Apr 17 09:20 temurin-17.jre
drwxr-xr-x  3 root  wheel  96 Apr 17 19:45 temurin-21.jre

Should I remove one of the older ones?  Is there something else I should install?
(thanks, I'm really out of my pay grade right now. :-)

**Comment by lart2150** [comment]
I would remove "jdk1.8.0_121.jdk" and "temurin-11.jdk" as they are both super out of date.

It looks like Marcos is supposed to pick the latest version of java by default.  if you switch the jdk 22 you'll need to nuke javafx-sdk if you have it so kmttg will download javafx 20.

what does `/usr/libexec/java_home -V` show?

**Comment by lart2150** [comment]
I just now realized you said macos 10.13.  I'm not sure what version of java supports macos 10.13 but recent versions of javafx and openjdk require at least macos 11.  Any chance you can upgrade macos with something like OpenCore Legacy Patcher?

**Comment by allartburns** [comment]
Hm, I wonder if it's easier for me to just build v2.7 with the updated password.

**Comment by cookieguru** [comment]
> Hm, I wonder if it's easier for me to just build v2.7 with the updated password.

You can grab the build of any recent commit here:
https://github.com/lart2150/kmttg/actions
Click any build, scroll down to Artifacts

**Comment by lart2150** [comment]
> Hm, I wonder if it's easier for me to just build v2.7 with the updated password.

you could just use 2.7 and put the cdata files in the same folder as the jar  https://github.com/lart2150/kmttg/issues/13

**Comment by allartburns** [comment]
Forgot to answer this:

flatline:~ jet$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
flatline:~ jet$

**Comment by allartburns** [comment]
Ok, I fixed it by accident!   I followed the instructions on removing java:  https://www.java.com/en/download/help/mac_uninstall_java.html

Rebooted, then reinstalled the macos java app, then the oracle jre8u package and 2.8-i is working.

**Comment by lart2150** [comment]
Awesome glad you got it working with 2.8.  That JDK 6 would cause issues as kmttg is compiled for java 8+.
