### ISSUE TITLE
Revised certificate not in v2.8-l distribution

### ISSUE THREAD

**Issue by japageth** [lart2150/kmttg#24]
The revised security certificate files expiring in 2026 are not included in the latest [v2.8-l](https://github.com/lart2150/kmttg/releases/tag/v2.8-l) release.  Specifically, cdata.p12 and cdata.password.  I was able to find them in Closed Issue #13 but I don't think most users will think to look there.

**Comment by lart2150** [comment]
the 2026 cert is embedded in the jar.  if you have cdata files it will use that instead of what is embedded in the jar.

**Comment by lart2150** [comment]
2.8-l does have the 2026 cert however if you have a cdata file pair it will blindly use that even if it's older then the backed in one.
