### ISSUE TITLE
Error when trying to refresh playlist

### ISSUE THREAD

**Issue by wireman121** [lart2150/kmttg#25]
RemoteInit - (IP=192.168.100.137, port=1413): Connection reset by peer: socket write error
[java.net.SocketOutputStream.socketWrite0(Native Method), java.net.SocketOutputStream.socketWrite(Unknown Source), java.net.SocketOutputStream.write(Unknown Source), sun.security.ssl.SSLSocketOutputRecord.flush(Unknown Source), sun.security.ssl.HandshakeOutStream.flush(Unknown Source), sun.security.ssl.CertificateVerify$T12CertificateVerifyProducer.produce(Unknown Source), sun.security.ssl.SSLHandshake.produce(Unknown Source), sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(Unknown Source), sun.security.ssl.SSLHandshake.consume(Unknown Source), sun.security.ssl.HandshakeContext.dispatch(Unknown Source), sun.security.ssl.HandshakeContext.dispatch(Unknown Source), sun.security.ssl.TransportContext.dispatch(Unknown Source), sun.security.ssl.SSLTransport.decode(Unknown Source), sun.security.ssl.SSLSocketImpl.decode(Unknown Source), sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source), sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source), sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source), com.tivo.kmttg.rpc.TiVoRPC.RemoteInit(TiVoRPC.java:269), com.tivo.kmttg.rpc.TiVoRPC.<init>(TiVoRPC.java:106), com.tivo.kmttg.rpc.Remote.<init>(Remote.java:57), com.tivo.kmttg.rpc.Remote.<init>(Remote.java:69), com.tivo.kmttg.main.config.initRemote(config.java:634), com.tivo.kmttg.task.NowPlaying$1AutoThread.run(NowPlaying.java:90), java.lang.Thread.run(Unknown Source)]

**Comment by lart2150** [comment]
What version of kmttg are you running and do you have the cdata file files in your kmttg folder?

**Comment by wireman121** [comment]
just updated to 2.8-I

I do.  Interestingly enough, I just removed them from the folder and it started working again!

What are they?

**Comment by thess** [comment]
The cdata files are signed certificates (think public/private keys) which are used by kmttg to authenticate itself to your Tivo as a bona-fide remote client. In effect, kmttg is masquerading as (AFAIK) an Android Tivo App. Most PKI certificates have expiration dates; that is what we have to contend with for kmttg maintenance. 

In your case, the most likely cause was the one you had in the kmttg folder, which has precedence over the one baked in, had expired. The current certificate expires 1/24/2026 (previous just expired on 5/3/2024).
