### ISSUE TITLE
Extract 2024 cert

### ISSUE THREAD

**Issue by lart2150** [lart2150/kmttg#26]
I'm fairly confident the password is Ejasjdfiu23! and this is the mind cert but for some reason I just can't get it to open.

[mindcert.2024.p12.zip](https://github.com/lart2150/kmttg/files/15449118/mindcert.2024.p12.zip)

**Comment by thess** [comment]
It is certainly a pkcs12 file. The key is most likely incorrect. Note that previous keys are 10 chars long and this key is 12. It may not be the issue - just an observation.

**Comment by lart2150** [comment]
I also thought that was weird with the different password length but that seems to be what AndroidCertificateProvider is getting from TivoTvConfig right before it loads it into the java KeyStore :(

I pulled up a packet capture of the handshake and this cert expires on 11/17/2026 so it would only buy us about 10 more months compared to the current known cert (1/24/2026)
[cert 2026-11-17.zip](https://github.com/lart2150/kmttg/files/15462264/cert.2026-11-17.zip)

**Comment by lart2150** [comment]
well that was interesting

piUYKNH7Sb

**Comment by lart2150** [comment]
[cdata.zip](https://github.com/lart2150/kmttg/files/15484264/cdata.zip)

**Comment by lart2150** [comment]
fixed https://github.com/lart2150/kmttg/commit/22c0132b1a45ab4d4907cb68745306944235fb71
