### ISSUE TITLE
add tivo file id as one of the variables in the file naming drop down

### ISSUE THREAD

**Issue by lart2150** [lart2150/kmttg#28]
### Discussed in https://github.com/lart2150/kmttg/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **tweiner** July 18, 2024</sup>
I have some downloads that the file naming option make them identical.  Would it be possible to add some of the tivo internal flags like the tivo file id.  It is a unique number that would be helpful.</div>

**Comment by lart2150** [comment]
https://github.com/lart2150/kmttg/commit/e2ce82e5c693b556d49e30c9bff2462c4660d84e

**Comment by tweiner** [comment]
Thank you!!!!!
