### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by techpro2004** [lart2150/kmttg#3]
Just saw you updated the code to work with java 11. I was wondering which java implementation to use, oracle java 11 or openjdk 11 or something else. thanks.

**Comment by lart2150** [comment]
I'm using the adopt open jdk 11 and javafx 11 https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_windows-x64_bin-sdk.zip

I've also tested with  adopt open jdk 19 and javafx 19 https://gluonhq.com/products/javafx/.

I have not tested with oracle java 11 but if you have issues with it let me know and I can try and troubleshoot them.

to use javafx you'll need to add something to your command to tell the jre where openfx is and what modules to load.  this is what I use `--module-path "C:\Program Files\Eclipse Adoptium\javafx-sdk-11.0.2\lib" --add-modules javafx.web`

**Comment by techpro2004** [comment]
would it work with just the jre 11 and not fx. I am not sure what fx does. thanks

**Comment by lart2150** [comment]
The jre should be fine but you still need javafx.  javafx used to be bundled with the opendjk however that was removed as part of 9.  I've looked at removing the dependency on javafx but it would require a rewrite of all of the gui components so it is a longer term goal if ever.  I think the oracle jre/jdk still includes javafx.

**Comment by techpro2004** [comment]
I installed oracle jdk 11 but got the error popup about fx. I then tried that link you sent me and created a bat file with the line below but same error

kmttg.jar --module-path "C:\Program Files\Eclipse Adoptium\javafx-sdk-11.0.2\lib" --add-modules javafx.web

is there any way you could bundle javafx with kmttg and have it pre-configured. thanks.

**Comment by techpro2004** [comment]
hello

**Comment by lart2150** [comment]
Did you extract javafx to C:\Program Files\Eclipse Adoptium\javafx-sdk-11.0.2\

**Comment by techpro2004** [comment]
Yes I did.

**Comment by techpro2004** [comment]
hello

**Comment by techpro2004** [comment]
Just checking on this. thanks.

**Comment by lart2150** [comment]
I don't know what to tell you it worked for me on windwos, [jimdoc](https://www.tivocommunity.com/members/jimdoc.317714/) on macos, and [snerd](https://www.tivocommunity.com/members/snerd.207475/) on linux.

**Comment by techpro2004** [comment]
I see a few hours ago, you commeted a fix but no release, how do I test it.

**Comment by techpro2004** [comment]
got it to work. had to tweak the command a little. ended up using this:

java --module-path "C:\Program Files\Eclipse Adoptium\javafx-sdk-11.0.2\lib" --add-modules javafx.web -jar c:\kmttg\kmttg.jar

thanks
