### ISSUE TITLE
Issue when trying to use VideoReDo

### ISSUE THREAD

**Issue by oryandunn** [lart2150/kmttg#31]
I'm using v2.8-I and when I have selected VideoReDo, I receive the following error:
"The system cannot find the path specified
Failed to created lock file: null"

I have both VideoReDo 5 and 6 installed, and get the same error with both.  This has worked with past versions of kmttg.  I'm only trying to decrypt and qsfix on my files.  I was looking for log files or more debug output to try to troubleshoot more, but haven't found any way to give more feedback.

**Comment by oryandunn** [comment]
Looking through the code, it looks like I'm hitting line 92 of qsfix.java when it's trying to create a temporary file.  Still investigating this....

**Comment by oryandunn** [comment]
Ok, it was definitely temp file relates.  I was able to relaunch from the command line in an environment with a known TEMP variable set, and the program was able to create the lock file.  In the case where the file was created and the VRD scripts run, the temp/lock file path is shown, for example 
"/l:C:\USERS\RYAN\APPDATA\LOCAL\TEMP\kmttg_temp\VRDLock7938582291595464484.tmp"

However, it would be nice if in the case that the temp/lock file is unable to be created, that the path it was attempting to use was printed to the log.

I was running kmttg by just double clicking on the jar file.  I have a feeling it was somehow trying to use the system temp folder, which my user doesn't have permission to write to, but that's just a guess since I don't know where the failed lock files were attempting to be written to.

**Comment by lart2150** [comment]
That's odd.  On windows TEMP should point to your user temp folder.  on start kmttg should make the kmttg_temp folder and then nuke everything in that folder.  Do you have a kmttg_temp folder?

https://github.com/lart2150/kmttg/blob/master/src/com/tivo/kmttg/main/config.java#L711-L722
