### ISSUE TITLE
tiny print

### ISSUE THREAD

**Issue by brendag4** [lart2150/kmttg#4]
I installed this version of KMTTG over a previous version. I am on a new computer. Windows 11

The print is very small

**Comment by lart2150** [comment]
Can you provide some more information?

- What jre are you running (version and who distributes it)
- what javafx are you using (version and who distributes it)
- what display scaling you are using on windows

**Comment by brendag4** [comment]
- what display scaling you are using on windows

250% it says it is the recommended setting. 3840x2400

When I put it at 1920x1080 it is back to normal. Is there a way to do it
without having to manually change the resolution?

**Comment by lart2150** [comment]
when I get home I'll have to play around some but can you try adding this before -jar `-Dsun.java2d.uiScale=2.5`

**Comment by brendag4** [comment]
Where do I put the above info? I am just clicking on the kmttg jar file to
access it.

I thought Java was only supported up to v8. I read something that seemed to
say I could use v11. I am using v8. Which should I use?

**Comment by lart2150** [comment]
I just tested on my computer using oracle java 1.8 b341, openjdk 11 with javafx 11, and opendjk 17 with javafx 17 and all three scaled correctly on windows 11 (22h2) and even correctly rescaled when dragged from one screen to another.

**Comment by brendag4** [comment]
Did you try it on a 4k computer?

Attached is my version

**Comment by brendag4** [comment]
Here is a loom video showing what happens

https://www.loom.com/share/ced18934f1f24036bdc5c0abc1531212

**Comment by lart2150** [comment]
I don't have a 4k display handy.  Can you tell me what jra version you are using?

**Comment by brendag4** [comment]
How do I find out the jra? How do I enter the string you gave me previously
-jar etc? Is it from the command line?

**Comment by lart2150** [comment]
sorry JRE not jra.

"java -version" from command line. it should output something like

 java -version
java version "**1.8.0_341**"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

**Comment by brendag4** [comment]
I thought the picture I sent had that info about versions

Is version 8 the one I should be using?

**Comment by lart2150** [comment]
I don't see screenshot in your comment https://github.com/lart2150/kmttg/issues/4#issuecomment-1368156608

can you try the version I posted? https://download.oracle.com/otn/java/jdk/8u341-b10/424b9da4b48848379167015dcc250d8d/jdk-8u341-windows-x64.exe

**Comment by brendag4** [comment]
I installed this version of KMTTG over a previous version. I am on a new computer. Windows 11

qsfix failed (exit code: 0 ) - check command: C:\WINDOWS\system32\cscript.exe //nologo "C:\kmttg lenovo\VRDscripts\qsfix.vbs" "C:\kmttg lenovo\Star Trek The Next Generation - s05e06 - The Game (2022-08-01_2104).TiVo" "C:\kmttg lenovo\Star Trek The Next Generation - s05e06 - The Game (2022-08-01_2104).ts.qsfix" /l:C:\Users\brend\AppData\Local\Temp\VRDLock4940638843630754542.tmp /m /c:mpegts /v:mpeg2video /x:704 /y:480 
C:\kmttg lenovo\VRDscripts\qsfix.vbs(155, 5) (null): The remote procedure call failed.

**Comment by brendag4** [comment]
I guess the picture did not upload because I have been responding from email. Now I will try to add from Github.

![java about](https://user-images.githubusercontent.com/121461795/210312320-a09e9773-23c9-4895-9e48-d89851461755.png)

**Comment by lart2150** [comment]
In case you have more than one version of java installed can you try running the two following commands from the kmttg folder in either powershell or the command prompt? "java -version" and then "java -jar kmttg.jar" instead of double clicking on the jar.

**Comment by brendag4** [comment]
here is what I got

![java version](https://user-images.githubusercontent.com/121461795/210492752-e4ab7a91-2270-40a9-9cdf-f8055ad81757.png)

**Comment by lart2150** [comment]
That's very weird.  If you change the windows screen scaling (to say 150 or 100) but keep your display at 4k does the text in kmttg get even smaller or does it stay the same size?

**Comment by brendag4** [comment]
I had the window smaller than the full screen. When I changed the scale, it made the window smaller but the text stayed the same size.

**Comment by brendag4** [comment]
What should I try now?

**Comment by lart2150** [comment]
I don't know. for some reason dpi scaling is not working for you but it works fine for me.
