### ISSUE TITLE
Hover help in configuration and file naming issue

### ISSUE THREAD

**Issue by christoney** [lart2150/kmttg#6]
Installed the latest [v2.6-l] the other day. Using Windows 10 Pro desktop. Java version "1.8.0_241"
Light mode from settings/Personalization/colors/choose your color/light. See attached png.

The hover help is like 85% black. Is there a way to fix or change that? 

Additionally I am using the file naming template [mainTitle][/][SeriesEpNumber] - [episodeTitle] 
BUT what I always get is this Counting Cars - ''Alice Cooper's Dream'' (Recorded Dec 20, 2022, KPXMDT6)
I'd like to know how to get the correct naming. It is persistent and comes up no matter what encoding profile I try. 

Thanks lart2150 for keeping this great tool going. 

![config issues](https://user-images.githubusercontent.com/26290485/210027219-99d9c7a4-9280-49eb-b403-75148967b2c5.png)

**Comment by brian163** [comment]
+1 regarding the hover help. I use it all the time and it's practically unreadable as show in @christoney 's screenshot.

**Comment by lart2150** [comment]
Ugg I had to change how the css is loaded to support javafx on java 11 or higher.  I'll have to fire up java 8 to see what I can do.

**Comment by lart2150** [comment]
:( I thought I fixed that before I pushed the release.  This was fixed with commit https://github.com/lart2150/kmttg/commit/3c56365979f265f84064bd33c0c92885f5d6af87 

give this build a try
[kmttg_20221211-1227.zip](https://github.com/lart2150/kmttg/files/10328075/kmttg_20221211-1227.zip)

**Comment by brian163** [comment]
Back to black text on yellow background. Looks good to me. Thanks!

**Comment by christoney** [comment]
Thanks Brian, checking on my end too.

**Comment by christoney** [comment]
Confirmed black text on yellow field. Thanks lart2150! 
For my next trick, I'm trying this for my file naming problem/variable:
[mainTitle][/][mainTitle] -[" " movieYear "][" " SeriesEpNumber " "]["- " episodeTitle] [originalAirDate]

**Comment by lart2150** [comment]
[mainTitle][/][mainTitle] -[" " movieYear "][" " SeriesEpNumber " "]["- " episodeTitle] [originalAirDate]
gives me
Cooks Country\Cooks Country - s12e02 - Italian Comfort Food Classics 2019-08-31.ts
and
Wont You Be My Neighbor\Wont You Be My Neighbor - 2018 2019-02-09.ts

So that is working for me.

**Comment by christoney** [comment]
Thanks lart2150. Scratching my head on this one. For some reason I still get the damn recorded and channel info in parenthesis.
