### ISSUE TITLE
service crashes java 11

### ISSUE THREAD

**Issue by techpro2004** [lart2150/kmttg#9]
since switching to java 11, the service keeps crashing. I have attached logs and config. thanks.
[logs.zip](https://github.com/lart2150/kmttg/files/10369202/logs.zip)

**Comment by lart2150** [comment]
I looked through the logs and I don't see anything obvious.  Do you have some times it crashed so I can better look at the logs?

**Comment by techpro2004** [comment]
It should be the last thing in the logs. My guess based on how quickly it crashes is it is failing some sort of pre launch check or a config error. the crash is fixed by installing java 8 but this is not an acceptable solution. thanks

**Comment by lart2150** [comment]
I don't see anything obvious in the logs.  can you try running with -d in addition to -a or -b to see if the standard out might provide more info.

**Comment by techpro2004** [comment]
the results are as follows:

-d and -a

>>>autoConfig.java: com.tivo.kmttg.main.autoConfig.parseAuto(line 45): config=C:\kmttg\auto.ini
>>>file.java: com.tivo.kmttg.util.file.isFile(line 49): f=C:\kmttg\auto.ini
>>>autoConfig.java: com.tivo.kmttg.main.autoConfig.parseAuto(line 212): entry={type=title, tivo=all, keyword=.*, keywords=[]}

-a and -b

>>>log.java: com.tivo.kmttg.util.log.getDetailedTime(line 244):
TOTAL auto matches for 'BOLT VOX' = 384/386
>>>log.java: com.tivo.kmttg.util.log.getDetailedTime(line 244):
NPL job completed: 0:00:11
>>>log.java: com.tivo.kmttg.util.log.getDetailedTime(line 244):
---DONE--- job=playlist tivo=BOLT VOX
>>>log.java: com.tivo.kmttg.util.log.getDetailedTime(line 244):
>>>SkipManager.java: com.tivo.kmttg.rpc.SkipManager.skipEnabled(line 61):
Shutdown hook executing
SHUTTING DOWN
>>>log.java: com.tivo.kmttg.util.log.getDetailedTime(line 244):




I noticed -d -b ran and exited on it's own. -d -a repeated over and over again.

**Comment by lart2150** [comment]
I don't see anything obvious.  I'll need to make a build with a bunch of debug logs.

**Comment by techpro2004** [comment]
sounds good. let me know when it is done. thanks.

**Comment by techpro2004** [comment]
I noticed in services.msc the command is C:\kmttg\service\win32\bin\wrapper.exe -s C:\kmttg\service\conf\wrapper.conf

I tried running it in cmd

C:\Users\techpro2004>C:\kmttg\service\win32\bin\wrapper.exe -s C:\kmttg\service\conf\wrapper.conf
Attempting to start kmttg as an NT service.

Calling StartServiceCtrlDispatcher...please wait.

StartServiceControlDispatcher failed!

For help, type

C:\kmttg\service\win32\bin\wrapper.exe /?

**Comment by techpro2004** [comment]
event viewer reports the following

The kmttg service terminated with the following service-specific error: 
Incorrect function.


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<SCRIPT>
  
    function Toggle(node)
    {
      if (!window.fullyLoaded) return;

      var divNode = node.nextElementSibling;

      // nextElementSibling may unexpectedly return null
      if (!divNode) divNode = node.nextSibling;
      if (!divNode || divNode.nodeType != 1) return;

      // Expand the branch?
      if (divNode.style.display == 'none')
      {
        // Change the sign to "-".
        var bNode = node.getElementsByTagName("b")[0];
        bNode.innerText = "-";

        // show the branch
        divNode.style.display = '';
      }
      else // Collapse the branch
      {
        // Change the sign to "+".
        var bNode = node.getElementsByTagName("b")[0];
        bNode.innerText = "+";

        // hide the branch
        divNode.style.display = 'none';
      }
    }

    // Toggle "System" element by default so that its default status is to hide its children
    function ToggleSystemElement()
    {
      var body = document.getElementById("body");
      var anchor = body.getElementsByTagName("table")[0];
      Toggle(anchor);
    }

    // If binary data is present in event XML, show it in friendly form.
    function ProcessBinaryData(binaryString, binaryDataCaption, wordsFormatString, bytesFormatString, normalFont, fixedWidthFont)
    {
      var bodyNode = document.getElementById("body");

      // Add a <hr> at the end of the HTML body.
      bodyNode.appendChild(document.createElement("hr"));      

      // This paragraph (p element) is the "Binary data:" literal string.
      var p = document.createElement("p");
      p.style.fontFamily = normalFont;
      var b = document.createElement("b");
      b.appendChild(document.createTextNode(binaryDataCaption));
      p.appendChild(b);
      p.appendChild(document.createElement("br"));
      bodyNode.appendChild(p);

      //
      // Show binary data in Words format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(wordsFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      var i = 0;
      var j = 0;
      var s, tempS;
      var translatedString;
      var charCode;
      var byte1, byte2;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte; 4 characters for a word.
      while (i < binaryString.length) {

        s = (i / 2).toString(16);    // To hex representation.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // DWords representation is simply a rearrangement of the original binaryString
        // For example, from:
        // 
        // 0000000002005600000000000f000540
        //
        // (which is 00 00 00 00 02 00 56 00 00 00 00 00 0f 00 05 40).
        //
        // to:
        //
        // 0000: 00000000 00560002 00000000 4005000f
        // 8 words per line, 4 DWords per line.
        for (j = 0; j < 4; j++) {
          s += binaryString.substring(i + 6, i + 8);
          s += binaryString.substring(i + 4, i + 6);
          s += binaryString.substring(i + 2, i + 4);
          s += binaryString.substring(i, i + 2) + " ";
          i += 8;
        }

        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);

      //
      // Show binary data in bytes format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(bytesFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      i = 0;
      j = 0;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte.
      while (i < binaryString.length) {
        translatedString = "";
        // 2 characters in binaryString to form a byte
        s = (i / 2).toString(16);   // to hex representation.

        // Prefix with '0' until its length is 4.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // Show 8 bytes per line
        for (j = 0; j < 8; j++) {
          tempS = binaryString.substring(i, i + 2); // 2 for 1 byte
          i += 2;
          s += tempS + " ";

          // Treat tempS as hex integer
          charCode = parseInt(tempS, 16);
          if (charCode < 32) {
            translatedString += ".";
          } else {
            translatedString += String.fromCharCode(charCode);
          }
        }

        while (s.length < 32) {
          s += " ";
        }
        s += translatedString;
        
        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);
    }
  
  </SCRIPT>
</HEAD>
<BODY id=body 
onload="window.fullyLoaded='true'; ToggleSystemElement(); ProcessBinaryData('6B006D007400740067000000', 'Binary data:', 'In Words', 'In Bytes', 'Segoe UI', 'Courier New')"><TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>System</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Provider</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Name</B>] </TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Service Control 
Manager</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Guid</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">{555908d1-a6d7-4695-8e1e-26931d2012f4}</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>EventSourceName</B>] </TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Service Control 
Manager</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">7024</TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Qualifiers</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">49152</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Version</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Level</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Task</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Opcode</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Keywords</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0x8080000000000000</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>TimeCreated</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>SystemTime</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2023-01-11T18:00:41.1433409Z</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventRecordID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">385464</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'"><B>Correlation</B></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Execution</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ProcessID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">1124</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ThreadID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">16444</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Channel</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">System</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Computer</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">overseer1</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'"><B>Security</B></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></DIV>
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventData</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>param1</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">kmttg</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>param2</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">%%1</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">6B006D007400740067000000</TD></TR></TBODY></TABLE></DIV>
<HR>

<P style="FONT-FAMILY: Segoe UI"><B>Binary data:</B><BR></P>
<P style="FONT-FAMILY: Segoe UI">In Words</P>
<P style="FONT-FAMILY: Courier New">0000: 006D006B 00740074 00000067  <BR></P>
<P style="FONT-FAMILY: Segoe UI">In Bytes</P>
<P style="FONT-FAMILY: Courier New">0000: 6B 00 6D 00 74 00 74 00   
k.m.t.t.<BR>0008: 67 00 00 00               g...<BR></P></BODY></HTML>

**Comment by lart2150** [comment]
Do you have another error right before that that says 
```The kmttg service is marked as an interactive service.  However, the system is configured to not allow interactive services.  This service may not function properly.```

I had to do this to start the service on my computer https://wrapper.tanukisoftware.com/doc/english/integrate-simple-win.html

**Comment by techpro2004** [comment]
I do have that error sometimes but not all the time. That first link did not give any instructions aside from modifying the conf file which I do not feel comfortable doing. I look forward to testing your alternative solution. thanks.

**Comment by thess** [comment]
I have been upgrading my Win10/11 system to Java 11 and have given up on the Win32 service wrapper included in kmttg -- It doesn't work very well with 64-bit Java at all and the JSW provider wants a fortune for the 64-bit version.

I have tried some of the other packages mentioned in the thread and they either don't work very well or are way to hard to use. The best utility I have come across is WinSW (https://github.com/winsw/winsw). It is very simple to configure and use -- and actively maintained. Version 2.11 has downloadable binaries posted. You only need 2 files to make this work: The WinSW executable and a configuration file.

I am working on an integration with kmttg  _"Auto Transfers"->Service_ functions. Attached is my current configuration file (remove **.txt** extension). I use the system defined logical JFX_LIB for launching kmttg with the necessary arguments. In my case this is: ```JFX_LIB=C:\Program Files\Java\javafx-sdk-11.0.2\lib```

[kmttg-svc.xml.txt](https://github.com/lart2150/kmttg/files/10417950/kmttg-svc.xml.txt)

**Comment by lart2150** [comment]
@thess : javafx should not be needed with the latest builds in auto mode.


@techpro2004 : procrun seems to work can you try something for me?  First uninstall the current service then follow the following directions.  if it works for you too I'll script it up.

1. download https://downloads.apache.org/commons/daemon/binaries/windows/commons-daemon-1.3.3-bin-windows.zip
2. extract it to C:\kmttg\service\win32\apache
3. in an elevated command prompt run ```C:\kmttg\service\win32\apache\amd64\prunsrv //IS//kmttg --DisplayName="kmttg" --Install=C:\kmttg\service\win32\apache\amd64\prunsrv.exe --Jvm=auto --StartMode=jvm --Classpath=%CLASSPATH%;C:\kmttg\kmttg.jar --StartClass=com.tivo.kmttg.main.kmttg --StartParams=-a```

**Comment by techpro2004** [comment]
the service starts but it hangs immediately and wont stop in services.msc. I have to kill it in task manager it also does not download recordings. How do i remove this service.

**Comment by lart2150** [comment]
Can you try this to start it this way first to see if there are any useful errors?
C:\kmttg\service\win32\apache\amd64\prunsrv //TS//kmttg

This will delete the service
C:\kmttg\service\win32\apache\amd64\prunsrv //DS//kmttg

You can also try killing prunsrv.exe from the task manager.  I would need to do a bit more work to get it to cleanly stop.

**Comment by thess** [comment]
```[2023-01-14 14:44:47] [warn]  [ 4672] Failed to grant service user 'NT AUTHORITY\LocalService' write permissions to log path 'C:\Windows\system32\LogFiles\Apache' due to error '19: The media is write protected.'```

Same for `--ServiceUser=LocalSystem`

Not sure what this is, but the service gets installed and runs a bit then exits when started. (javafx again?)

```c:\kmttg\service\prunsrv //TS/kmttg

STARTING AUTO TRANSFERS
>> Getting Now Playing List from Tivo HDXL ...
https://10.0.2.45/TiVoConnect?Command=QueryContainer&Container=/NowPlaying&Recurse=Yes&ItemCount=32&AnchorOffset=0
>> Getting Now Playing List via RPC from Den Bolt ...

'Tivo HDXL' PROCESSING SLEEPING 30 mins ...

'Den Bolt' PROCESSING SLEEPING 30 mins ...
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/event/EventHandler
        at com.tivo.kmttg.util.parseNPL.rpcToHashEntry(parseNPL.java:447)
        at com.tivo.kmttg.task.NowPlaying.rpcToNPL(NowPlaying.java:174)
        at com.tivo.kmttg.task.NowPlaying.check(NowPlaying.java:151)
        at com.tivo.kmttg.main.jobData.check(jobData.java:333)
        at com.tivo.kmttg.main.jobMonitor.monitor(jobMonitor.java:147)
        at com.tivo.kmttg.main.auto.startBatchMode(auto.java:132)
        at com.tivo.kmttg.main.kmttg.main(kmttg.java:126)
Caused by: java.lang.ClassNotFoundException: javafx.event.EventHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 7 more
Shutdown hook executing
SHUTTING DOWN
Killing 'javaplaylist' TiVo: Tivo HDXL
warn: Killing 'javaplaylist' TiVo: Tivo HDXL
```

I'm liking WinSW more by the moment.

**Comment by techpro2004** [comment]
I get the following error:


Exception in thread "main" java.lang.NoClassDefFoundError: javafx/event/EventHandler
        at com.tivo.kmttg.util.parseNPL.rpcToHashEntry(parseNPL.java:447)
        at com.tivo.kmttg.task.NowPlaying.rpcToNPL(NowPlaying.java:174)
        at com.tivo.kmttg.task.NowPlaying.check(NowPlaying.java:151)
        at com.tivo.kmttg.main.jobData.check(jobData.java:333)
        at com.tivo.kmttg.main.jobMonitor.monitor(jobMonitor.java:147)
        at com.tivo.kmttg.main.auto.startBatchMode(auto.java:132)
        at com.tivo.kmttg.main.kmttg.main(kmttg.java:126)
Caused by: java.lang.ClassNotFoundException: javafx.event.EventHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 7 more

**Comment by lart2150** [comment]
Great it looks like I need to fix a decency on javafx in com.tivo.kmttg.util.parseNPL.rpcToHashEntry as that is crashing for both of you.

**Comment by techpro2004** [comment]
sounds good. let us know when it is fixed. thanks.

**Comment by lart2150** [comment]
Can you give this build a try?  I still need to fix the service not stopping correctly.

[kmttg_20230114-1831.zip](https://github.com/lart2150/kmttg/files/10419159/kmttg_20230114-1831.zip)

**Comment by techpro2004** [comment]
service is up and staying up using wrapper.exe. recording a 30 min show will post back with if it downloads or not. thanks.

**Comment by techpro2004** [comment]
I waited 5 min after the recording stopped and no download, restarted the service and it downloaded. 5 min probably was not enough time. thank you for all of your help. Is there any way I can make a donation to help with development. thanks.

**Comment by thess** [comment]
Well, it kind-of works... I think I'll stick with the **WinSW** solution for now - it works just fine. I'd like to see your source updates because I need to build my version with some custom filtering (Ignore channels list and reduced logging of things it is not doing). I really do appreciate your work keeping this project alive!

1) Service does not install on win64. OS detection in install script is not correct. Try `%PROCESSOR_ARCHITECTURE%==AMD64`
2) Service termination leaves behind detached processes and auto.log is locked. At least the NPL temp files are no longer left behind.
3) The Apache code creates several unnecessary leavings in the registry and logs in the SystemRoot tree.
4) The install warning/error is distracting even though it appears to install OK - leave my system permissions alone.

**Comment by thess** [comment]
Ah - I just saw your check-ins (f5b9ce71210440134d32c5e73a88122b3843b3f9). Will give them a go. Thanks.

**Comment by techpro2004** [comment]
I am using the old wrapper.exe with the x64 jdk from above. It seems to work fine. the issue seems to have been the javafx dependency. not sure if apache is needed or maybe that is a different issue.

**Comment by lart2150** [comment]
I'll switch back to the old wrapper and give it a test.

**Comment by techpro2004** [comment]
sounds good. thanks. Let me know if you have any issues. I really appreciate all of your help and effort on this project and would like to paypal a small donation to you. please add a donations button to kmttg.

**Comment by techpro2004** [comment]
finished a recording 40 min ago, just autodownloaded. things are looking good.

**Comment by techpro2004** [comment]
just wondering what you decided.

**Comment by techpro2004** [comment]
hello

**Comment by techpro2004** [comment]
hello

**Comment by lart2150** [comment]
I just tested with the old service and your right it looks like with the code change it works fine so i'll revert back to the old service.
